# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TempoCli < Formula
  desc "AI code attribution for git commits"
  homepage "https://github.com/usetempo/tempo-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/usetempo/tempo-cli/releases/download/v0.1.0/tempo-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "d556730167361a72005a65edd0a87e8dd1456c1f4035885615de3e32afdc6318"

      def install
        bin.install "tempo-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/usetempo/tempo-cli/releases/download/v0.1.0/tempo-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "664b6dd3a161f930e541e7ed43922518e604f488c14ee00ce839410492aa1816"

      def install
        bin.install "tempo-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetempo/tempo-cli/releases/download/v0.1.0/tempo-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "b1a02026b206581b4b2e57c96273682c07f164e474017fc5c159574397ad77f6"
      def install
        bin.install "tempo-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/usetempo/tempo-cli/releases/download/v0.1.0/tempo-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "26495b7c27bd90f745b9a750308f4660bb3456b212d64694ba0cfde22b3477f3"
      def install
        bin.install "tempo-cli"
      end
    end
  end
end
